import { View } from '@porrtal/r-api';

export const porrtalIoViews: View[] = [
  {
    displayText: 'porrtal.io navigation',
    displayIcon: 'path-search',
    componentName: 'Nav',
    paneType: 'nav',
    launchAtStartup: true,
    componentModule: () => import('@porrtal-components/r-porrtal-io'),
  },
  {
    viewId: 'Welcome',
    displayText: 'Welcome !!',
    displayIcon: 'clean',
    componentName: 'Welcome',
    paneType: 'main',
    launchAtStartup: true,
    componentModule: () => import('@porrtal-components/r-porrtal-io'),
  },
  {
    viewId: 'Features',
    displayText: 'Features',
    displayIcon: 'clean',
    componentName: 'Features',
    paneType: 'main',
    componentModule: () => import('@porrtal-components/r-porrtal-io'),
  },
  {
    viewId: 'Docs',
    displayText: 'Docs',
    displayIcon: 'clean',
    componentName: 'Docs',
    paneType: 'main',
    componentModule: () => import('@porrtal-components/r-porrtal-io'),
  },
  {
    viewId: 'Events',
    displayText: 'Events',
    displayIcon: 'clean',
    componentName: 'Events',
    paneType: 'main',
    componentModule: () => import('@porrtal-components/r-porrtal-io'),
  },
  {
    viewId: 'Resources',
    displayText: 'Resources',
    displayIcon: 'clean',
    componentName: 'Resources',
    paneType: 'main',
    componentModule: () => import('@porrtal-components/r-porrtal-io'),
  },
  {
    viewId: 'BLOG',
    displayText: 'BLOG',
    displayIcon: 'clean',
    componentName: 'Blog',
    paneType: 'main',
    componentModule: () => import('@porrtal-components/r-porrtal-io'),
  },
];
