import { View, ViewComponentModules } from '@porrtal/api';

export const testModules: ViewComponentModules = {
  '@test-comps/first-test-comp': () => import('@test-comps/first-test-comp'),
  '@test-comps/second-test-comp': () => import('@test-comps/second-test-comp'),
};

export const testViews: View[] = [
  {
    viewId: 'one-nav',
    paneType: 'nav',
    launchAtStartup: true,
    componentName: 'TestCompsFirstTestComp',
    componentModule: '@test-comps/first-test-comp',
    key: 'one-nav',
    displayText: 'one',
    displayIcon: 'home',
  },
  {
    viewId: 'two-nav',
    paneType: 'nav',
    launchAtStartup: true,
    componentName: 'TestCompsFirstTestComp',
    componentModule: '@test-comps/first-test-comp',
    key: 'two-nav',
    displayText: 'two',
    displayIcon: 'settings',
  },
  {
    viewId: 'one-main',
    paneType: 'main',
    launchAtStartup: true,
    componentName: 'TestCompsFirstTestComp',
    componentModule: '@test-comps/first-test-comp',
    key: 'one-main',
    displayText: 'one',
    displayIcon: 'home',
  },
  {
    viewId: 'account-one',
    paneType: 'main',
    launchAtStartup: false,
    componentName: 'TestCompsFirstTestComp',
    componentModule: '@test-comps/first-test-comp',
    entityType: 'account',
    key: 'account-one',
    displayText: 'account-one',
    displayIcon: 'settings',
  },
  {
    viewId: 'account-two',
    paneType: 'main',
    launchAtStartup: false,
    componentName: 'TestCompsFirstTestComp',
    componentModule: '@test-comps/first-test-comp',
    entityType: 'account',
    key: 'account-two',
    displayText: 'account-two',
    displayIcon: 'settings',
  },
  {
    viewId: 'appointment-one',
    paneType: 'main',
    launchAtStartup: false,
    componentName: 'TestCompsFirstTestComp',
    componentModule: '@test-comps/first-test-comp',
    entityType: 'appointment',
    key: 'appointment-one',
    displayText: 'appointment-one',
    displayIcon: 'settings',
  },
  {
    viewId: 'three-main',
    paneType: 'main',
    launchAtStartup: true,
    componentName: 'TestCompsFirstTestComp',
    componentModule: '@test-comps/first-test-comp',
    key: 'three-main',
    displayText: 'three',
    displayIcon: 'account_circle',
  },
  {
    viewId: 'first-test-comp',
    paneType: 'main',
    launchAtStartup: true,
    componentName: 'TestCompsFirstTestComp',
    componentModule: '@test-comps/first-test-comp',
    key: 'first-test-comp',
    displayText: '@test-comps/first-test-comp',
    displayIcon: 'power',
  },
  {
    viewId: 'first-search-comp',
    paneType: 'search',
    launchAtStartup: true,
    componentName: 'TestCompsFirstTestComp',
    componentModule: '@test-comps/first-test-comp',
    key: 'first-search-comp',
    displayText: 'find stuff',
    displayIcon: 'power',
  },
];
