/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PorrtalRoleCreatedByDataAttributesRoles } from './porrtalRoleCreatedByDataAttributesRoles';
import { PorrtalRoleCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole } from './porrtalRoleCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole';


export interface PorrtalRoleCreatedByDataAttributes { 
    firstname?: string;
    lastname?: string;
    username?: string;
    email?: string;
    resetPasswordToken?: string;
    registrationToken?: string;
    isActive?: boolean;
    roles?: PorrtalRoleCreatedByDataAttributesRoles;
    blocked?: boolean;
    preferedLanguage?: string;
    createdAt?: string;
    updatedAt?: string;
    createdBy?: PorrtalRoleCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole;
    updatedBy?: PorrtalRoleCreatedByDataAttributesRolesDataInnerAttributesPermissionsDataInnerAttributesRole;
}

