/**
 * DOCUMENTATION
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact-email@something.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UsersPermissionsRolesGet200ResponseRolesInner } from './usersPermissionsRolesGet200ResponseRolesInner';


export interface UsersPermissionsRolesGet200Response { 
    roles?: Array<UsersPermissionsRolesGet200ResponseRolesInner>;
}

